jobs:
  - job: tests
    trigger: pull_request
    metadata:
        targets: [fedora-35]
        tmt_plan: /paths/fedora/35to36
        skip_build: true
  - job: tests
    trigger: pull_request
    metadata:
        targets: [fedora-36]
        tmt_plan: /paths/fedora/36to37
        skip_build: true
