jobs:

# Upgrade Paths

- job: tests
  trigger: pull_request
  targets: [fedora-40]
  tmt_plan: /paths/fedora40to41
  skip_build: true
  identifier: fedora40to41

- job: tests
  trigger: pull_request
  metadata:
  targets: [fedora-41]
  tmt_plan: /paths/fedora41to42
  skip_build: true
  identifier: fedora41to42

# Full Upgrade

- job: tests
  trigger: pull_request
  targets: [fedora-40]
  tmt_plan: /plans/fedora40to41
  skip_build: true
  identifier: full-upgrade
