jobs:

# Upgrade Paths

- job: tests
  trigger: pull_request
  targets: [fedora-stable]
  tmt_plan: /paths/
  skip_build: true
  identifier: upgrade-path

# Full Upgrade

- job: tests
  trigger: pull_request
  targets: [fedora-43]
  tmt_plan: /plans/fedora43to44
  skip_build: true
  identifier: full-upgrade
